### ISSUE TITLE
Hint cash position changes depending on the shop that is used

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#10]
Let me start with that this is mostly a minor thing. But then again at times I happen to notice myself wondering when I have just pressed the _Hint your current cash_ button that _"where did the cash hint actually go?"_

This is most probably because the cash hint is displayed in two different locations depending on what shop is being used.
With Clothing and Vehicle shop the hint gets displayed on the lower center part of the screen, see:
http://s1370.photobucket.com/user/testusah123/media/vehicle_and_clothingshop_hint_cash_pos_zpswambgylb.jpg.html

and with Weapons shop the hint gets displayed on the (high) right hand side of the screen, see:
http://s1370.photobucket.com/user/testusah123/media/weaponshop_hint_cash_pos_zps6ojwgsgd.jpg.html

Is there a particular reason the hints are displayed in two different locations? If there is then how it is now is ok.

Otherwise, if possible I would suggest to use only one of the two methods for all three shops.

**Comment by Ppgtjmad** [comment]
> Is there a particular reason the hints are displayed in two different locations? If there is then how it is now is ok.

That's because for whatever reason when you create a camera (that is used in both vehicle & clothing preview), the hint command doesn't show up... in fact it does show up but outside of the camera view if that makes sense. So I add to workaround this by using titleText instead hence why it's different.

**Comment by Asmodeuz** [comment]
Ahh, understood. I can guess from my short time with similar stuff that it can get a bit tricky to achieve certain things in Arma.

Thank you again for clearing this one up!
