### ISSUE TITLE
Money & Gear "hacking"

### ISSUE THREAD

**Issue by Ppgtjmad** [Ppgtjmad/SimpleShops#11]
If you try the mission in editor, the money & gear variables are set in the profileNamespace, then you can add more money & set the gear you want on your player then save it.

If you then leave the editor and connect to a server that has got SimpleShops system implemented, you'll get the same money & gear back from when you used the editor... that means you can have 1.000.000.000 cash & full gear...

So I'm gonna implement server sided profileNamespace saving to counter that.

Made this ticket myself because it's worth mentioning.

**Comment by SLIgaming** [comment]
Can you release A install pack for just this. Or what files to add ? Just this has been modified

**Comment by Ppgtjmad** [comment]
No need for two versions, it will work on dedicated & multiplayer (local hosting) & in editor when previewing. Am on it right now :)

**Comment by SLIgaming** [comment]
Nice mate gw ! You don't mind me editing the script do you?

**Comment by Ppgtjmad** [comment]
I don't mind, as long as you leave scripts header it's fine :+1:

**Comment by Ppgtjmad** [comment]
Should be fixed now, everything is on the server, need confirmation.

**Comment by SLIgaming** [comment]
Ill check it out now mate. I'll report back asap
