### ISSUE TITLE
enableTeamKillPenalty 

### ISSUE THREAD

**Issue by SLIgaming** [Ppgtjmad/SimpleShops#12]
This is not working with AI or MP. I guess it runs via "this call HG_fnc_aiUnitSetup;" in unit init. Its giving me reward for KillReward instead.

**Comment by Ppgtjmad** [comment]
Will have to test this, thanks for reporting.

**Comment by SLIgaming** [comment]
No problem mate ! this is a big part in my new project so I'll run alot of tests for you.

**Comment by SLIgaming** [comment]
Just so you know its either fn_addOrSubCash, fn_aiUnitSetup or fn_killed. I'm trying to edit to work on a fix myself. Ill let you know if i work it out

**Comment by Ppgtjmad** [comment]
Yeah it's stll not fixed because I didn't have a look at it. Will do later today.

**Comment by Ppgtjmad** [comment]
Should be fixed now https://github.com/Ppgtjmad/SimpleShops/commit/1fca4de93d8361425f7a39c994fcba75839f60c3

**Comment by SLIgaming** [comment]
Working Perfect  :) All thats needed now is the extDB3 ;) Thanks mate and good luck !!
