### ISSUE TITLE
Admin panel 

### ISSUE THREAD

**Issue by SLIgaming** [Ppgtjmad/SimpleShops#14]
admins[] = {"UID1","UID2","UID3"}; Is that the format ? what is the admin panel KeyDown?

**Comment by Ppgtjmad** [comment]
Yeah, totally forgot to mention the key... left windows key, will add it configurable.

**Comment by SLIgaming** [comment]
Awesome great work !

**Comment by SLIgaming** [comment]
I can confirm this is not working.

**Comment by Ppgtjmad** [comment]
It does work, tested in editor/player hosted and on dedicated. Definitely works.

**Comment by SLIgaming** [comment]
admins[] = {"76561198121738616"};
adminKey = 0xC7;

so thats what i have in config and my player UID is correct but still nothing. I'm aware I switched to home key and tried the default window but nothing. what do you mean by  PUID is equal to "SP_PLAYER" ?

**Comment by Ppgtjmad** [comment]
I mean that when you try it in editor/singleplayer **getPlayerUID player** command returns "_SP_PLAYER_" so you have to put this in the admins array to be able to open the admin menu.

```
admins[] = {"_SP_PLAYER_","76561198121738616"};
```

This way it will work in both single & multi player.

**Comment by SLIgaming** [comment]
Awesome mate all is working.I suggest mentioning that in the in the read me. Great work !

**Comment by SLIgaming** [comment]
Hey mate just tested this on my dedi and not working?
