### ISSUE TITLE
Admin not working on dedi 

### ISSUE THREAD

**Issue by SLIgaming** [Ppgtjmad/SimpleShops#15]
Now wont work on my dedi and error from server rpt:
 Error Undefined variable in expression: hg_fnc_parsegear
File mpmissions\__cur_mp.Altis\HG\Setup\fn_playerServerInitialization.sqf, line 98

**Comment by Ppgtjmad** [comment]
Basically the function (variable) isn't defined, make sure you have:

```
class CfgFunctions 
{
	#include "HG\Functions\HG_Functions.h"
};
```

In your **description.ext**

**Comment by SLIgaming** [comment]
I have to include them manually or i get error CfgFunctions already defined. And i can confirm the money is not updated after a purchase

**Comment by SLIgaming** [comment]
been running test all night with even default settings

**Comment by SLIgaming** [comment]
class CfgFunctions
{
	class myTag
	{
		class myCategory
		{
			class skipBriefing
			{
				file = "skipBriefing.sqf";
				preInit = 1;
			};
		};
	};
class HG
{
	class AdminMenu
	{
		file = "HG\Functions\AdminMenu";
		class adminMenuBtns {};
		class adminMenuListChanged {};
		class checkboxChanged {};
		class dialogOnLoadAdminMenu {};
		class refreshPlayers {};
	};
	
	class AI
	{
	    file = "HG\Functions\AI";
		class aiUnitSetup {};
	};
	
	class ClothingShop
	{
		file = "HG\Functions\ClothingShop";
		class buyClothing {};
		class clothingSelectionChanged {};
		class dialogOnLoadClothing {};
		class dialogOnUnloadClothing {};
		class fillBox {};
		class reset {};
		class xClothingSelectionChanged {};
	};
	
	class EVH
	{
		file = "HG\Functions\EVH";
		class handleRating {};
		class inventoryClosed {};
		class inventoryOpened {};
		class killed {};
		class respawn {};
	};
	
	class Garage
	{
		file = "HG\Functions\Garage";
		class delVehicle {};
		class dialogOnLoadGarage {};
		class fillGarage {};
	    class garageBtns {};
		class refreshGarage {};
		class storeVehicleC {};
	};
	
	class Generic
	{
		file = "HG\Functions\Generic";
		class addOrSubCash {};
		class addOrSubKills {};
		class addOrSubXP {};
	    class currencyToText {};
		class getConfig {};
		class getGear {};
		class hasEnoughMoney {};
		class isNumeric {};
		class markers {};
		class parseGear {};
		class paycheck {};
		class setOwner {};
		class setRank {};
	};
	
	class GiveMoney
	{
		file = "HG\Functions\GiveMoney";
		class giveMoneyBtn {};
	};
	
	class HUD
	{
		file = "HG\Functions\HUD";
		class HUD {};
	};
	
	class Tags
	{
		file = "HG\Functions\Tags";
		class playerTags {};
	};
	
	class VehiclesShop
	{
		file = "HG\Functions\VehiclesShop";
		class addActions {};
		class buyVehicle {};
		class dialogOnLoadVehicles {};
		class dialogOnUnloadVehicles {};
		class isItBusy {};
		class vehicleRotate {};
		class vehicleSelectionChanged {};
		class xVehicleSelectionChanged {};
	};
	
	class WeaponsShop
	{
		file = "HG\Functions\WeaponsShop";
		class dialogOnLoadItems {};
		class handleItems {};
		class itemBtns {};
		class itemSelectionChanged {};
		class xItemSelectionChanged {};
	};
    };
};

**Comment by Ppgtjmad** [comment]
Nothing wrong here, make sure you have the whole HG folder in mission root not other place

<Mission Root>\HG

**Comment by SLIgaming** [comment]
Yup it is. Trying all sorts but nothing

**Comment by SLIgaming** [comment]
All is working now 100% had to move everything out of discription.ext to #Include ( My own defines ) Unless you changed something between now and the last reply. Good work mate. 1 thing do i need to make a mySQL.sql file to Incorp the HG_money save using the extDB?

**Comment by SLIgaming** [comment]
Or will it automatic make its class if i setup the extDB and mySQL database?

**Comment by SLIgaming** [comment]
Also I made this using the HG_Cash system :)

`_pilot = (_this select 0);

private _price = 25000;

if([_price] call HG_fnc_hasEnoughMoney) then
{
     //Jet price sub
      [25000,1] call HG_fnc_addOrSubCash;
	 
    _jet = createVehicle ["B_Plane_CAS_01_F", [14359.506,26968.678,1200.000], [], 0, "FLY"]; //Fix flying height and position
  
    _pilot moveInDriver _jet;
	removeBackpack _pitlot;
	_Pilot addBackpack "B_parachute";
	
     hint format ["%1 \nYou have brought A10 Good Luck!",name _pilot];
    } else {
	 hint format ["%1 \nYou don't have enough mulah!",name _pilot];
};`

**Comment by Ppgtjmad** [comment]
I'm closing this issue, if you have things to add go on our forums, thanks!
