### ISSUE TITLE
example mission more details?

### ISSUE THREAD

**Issue by roby7979** [Ppgtjmad/SimpleShops#17]
hi ,very nice work for simple shop,i donwload and try it..but very very hard..maybe u can post a pbo with more details for understand how make it work in other missions? i cant understand how can change some parameters ..rewards for kills AI or other players,i cant see price of items,how can i set xp and level up..u can help me plz? thank you

**Comment by Ppgtjmad** [comment]
Hello,

Everything you need to know is here https://github.com/Ppgtjmad/SimpleShops/wiki

Tell me if you need more infos.
Thanks for using my shops.

**Comment by roby7979** [comment]
I have already read all,but if possible need more help,i Made over 30 missions but nothing with this system and your system is very nice!i wish learn :D the problems i find: to set AI or players kills for xp and money up(where must write line code?) cant find prewiev of price items but i saw there is in your vídeo maybe have some description with more details for not so expert guy? Thank you very much

**Comment by roby7979** [comment]
if u have some more details or example about this 2 problems that i cant understand u can send me plz in email stanzabarca@hotmail.com thank you very much

**Comment by Ppgtjmad** [comment]
I removed your e-mail for security reasons, you can contact me on Steam if you want -> HoverGuy AKA PeePee

**Comment by roby7979** [comment]
Ok thank you
