### ISSUE TITLE
Using has enough in statement ? 

### ISSUE THREAD

**Issue by SLIgaming** [Ppgtjmad/SimpleShops#18]
I want to return a false in a (if) statement but how do I call this ? 
Would this work ? 
`_hasEnough = [_value] call HG_fnc_hasEnoughMoney;
if (hasEnough = false) then { my code };`

**Comment by Ppgtjmad** [comment]
Hello,

The function itself returns true or false already:

```
_hasEnough = [5] call HG_fnc_hasEnoughMoney;

if (_hasEnough) then
{
    // Yay I can buy me candies
} else {
    // Am a poor boy...
};
```

If you need support, please go on our forums, ticket system is for issues only. Thanks :)

**Comment by SLIgaming** [comment]
Roger that mate mark as solved. cheers
