### ISSUE TITLE
Possibility to buy vehicle to garage but not necessarily the possibility to access the garage

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#19]
It is possible to buy a vehicle from the vehicle shop and store it directly to the garage with a button that is dedicated to this feature. See: http://i1370.photobucket.com/albums/ag278/testusah123/simpleshopsgarage_zps5jvgxmfk.jpg

If the mission maker doesn't declare
`this addAction["<img image='HG\UI\Icons\garage.paa' size='1.5'/><t color='#FF0000'>Open Garage</t>",{_this call HG_fnc_dialogOnLoadGarage},"HG_DefaultGarage",0,false,false,"",'(alive player) && !dialog && player distance _target < 3'];`
there is the possibility that players will buy vehicles directly to garage (by mistake or whatever reason) but then they won't have any chance to access the garage nor the vehicle they bought.

One suggestion would be that the dedicated _buy to garage_ button would be toggleable eg. in the **HG_Config.h**

**Comment by Ppgtjmad** [comment]
Done :)
