### ISSUE TITLE
Some resolutions make the cash display in the HUD to clip outside the screen

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#2]
This is from a friend of mine. He's using a 16:10 monitor with a 1680x1050 resolution and while every other vanilla Arma's HUD "boxes" are in their rightfull place the Shop systems' cash display on the lower right corner clips out of the screen.

Here's an example picture of the situation http://s1370.photobucket.com/user/testusah123/media/UIclipping_zpspuwnnpgw.jpg.html

Also the shop dialogs clip out of the screen from left and right.

Naturally the player has the power to change the *Interface size* from Arma 3's video options but at least in the case of 16:10 monitors one has to go down to *very small* which does make the cash display to be fully displayed but also leads to Arma's HUD boxes to change place closer to the center of the screen.
Here's an example picture of that case http://i1370.photobucket.com/albums/ag278/testusah123/UIclipping1680-1050_interface-size_very-small_zps4fy3keeb.jpg~original

Anything that could be done about this? Or would you think that this could somehow be a user-made error?

*edit: I'm using a 16:9 screen (1920x1080 resolution) as a primary display and the cash amount is displaying correctly. But I do happen to have a 16:10 display (with 1680x1050 resolution) as a secondary screen and I was able to confirm what my friend is seeing, so the problem is not only on his end.*

**Comment by Ppgtjmad** [comment]
Yeah am aware of that, the method am using for UI positioning is based off GUI_GRID.
It's only affected by interface size.

I'll switch to that soon -> [https://community.bistudio.com/wiki/pixelGrid] which has been implemented to replace said GUI_GRID.

**Comment by SLIgaming** [comment]
I've already done this you need to change GUI_GRID to i.e:
class MoneyText: HG_RscText
        {
            idc = HG_HUD_MONEY_TEXT_IDC;
            style = "0";
            shadow = 0;
            
            x = 0.95 * safezoneW + safezoneX;
            y = 0.84 * safezoneH + safezoneY;
            w = 1.35 * safezoneW;
            h = 0.04 * safezoneH;
            
            font = "PuristaMedium";
            sizeEx = 0.037;
            colorBackground[] = {0,0,0,0};
            colorText[] = {1,1,1,1};

in the C:\Users\Administrator\Desktop\KING_OF_THE_HILL.Altis\HG\UI\Dialogs HG_HUD.h ;)

**Comment by Ppgtjmad** [comment]
It's not a perfect solution because safeZone only takes screen resolution into account whereas pixelGrid takes both screen res & interface size.

But don't worry when I have time I'll change that.

**Comment by Ppgtjmad** [comment]
Should scale better in 2.2, needs confirmation.

**Comment by Asmodeuz** [comment]
I will provide one at some point. Can't offer any exact dates about _when_ though.

**Comment by Asmodeuz** [comment]
I tested this with the friend that was having issues with clipping UI assets and can now confirm that the new way of displaying UI dialogs got rid of that problem. So on our behalf we can say that this issue is now fixed.
