### ISSUE TITLE
Code Efficiency  

### ISSUE THREAD

**Issue by theace0296** [Ppgtjmad/SimpleShops#21]
For the fn_isNumeric.sqf:
Couldn't you just use **if((typename _Value) == "SCALAR")** to check if the number entered is a real number?

I feel like there's another reason to having this function setup this way, but I'm still learning the scripting side of Arma. I love the script and part of learning for me is figuring out how other coders think when writing their code, so any insight is helpful. 

~~As a side question, I'm also trying to allow the use of Static Weapons being bought in the script, and my only issue is I can't seem to get them to appear in the Garage.~~

Edit: I was able to figure out how to add static weapons, I had to modify **fn_getType.sqf** to include "StaticWeapons" in the _forEach_ command.

**Comment by Ppgtjmad** [comment]
Hello @theace0296 ,

Just because we don't want decimals hence why I have to filter out things.

```
_l = 0.555;
_p = (typeName _l) isEqualTo "SCALAR"; // Returns true but we don't want decimals...
```

**Comment by theace0296** [comment]
Ahh, I didn't think about the decimals. 
I guess another way to do that could be to:
```
params["_value",["_return",true]];

_roundedvalue = (round _value); //If _value is a number, it gets rounded. 
if((typename _roundedvalue) == "SCALAR") then //Will return true for any numeric _value
{
	_return = true;
}
else{};

_return;
```
Then in fn_addorSubX.sqf:
Change:
```
{
    case 0: 
	{
		_oldVal +  _amount;
	};
	case 1:
	{
		_oldVal - _amount;
	};
};
```
To:
```
{
    case 0: 
	{
		_oldVal + (round _amount);
	};
	case 1:
	{
		_oldVal - (round _amount);
	};
};
```

My interest was because I wanted to add more than 100000 to cash, and the current code says any number >100000 is a "non-number".
I know I could just set up a trigger to add_cash but it is always easier to do so in the Admin Menu.
Although I don't know which code is considered "more efficient" because I don't know how much the game is affected by either rounding or checking the values of a number.

**Comment by Ppgtjmad** [comment]
I just passed 150000 to the function and it returns true as it should, so where does it say any number >= 100000 is not a number?

Talking about efficiency, it doesn't really matter in this case, if it was a 100+ lines code OK but here we have  a very simple & lightweight function.

**Comment by theace0296** [comment]
In the admin menu when I tried to use the 'addcash' button. I passed it 1,000,000 (without the commas) and it returned an error. Also tried with 500000, 200000 with the same result.

**Comment by theace0296** [comment]
Using the "workaround" I posted above seems to have solved my issue. I will let you know if I encounter any issues with how I have it setup.
I don't really know why I was having an issue like that, but I've seen code work perfectly for some while the exact same code not working for others.


As a side question:
Would you mind if I posted in your forum instructions for getting ExtDB3 to work with Simple Shops?
I found most information about the topic to be centered around the Life and Wasteland servers, which while after a lot of work, did eventually get me a way to have the persistence to work. I wanted to be able to share my way of getting it to work with Simple Shops.

**Comment by Ppgtjmad** [comment]
Hello,

Yeah sure go ahead an post something it's always good to have references :)
