### ISSUE TITLE
Some players can not see the description texts and prices [MP]

### ISSUE THREAD

**Issue by TteMerino** [Ppgtjmad/SimpleShops#23]
Hi, i have a issue, when i open de admin panel in MP or SP, I do not see the texts, player names, or the description of these. Same case when I open the store of vehicles, weapons and clothes, I do not get the description of this, nor the price.

 The strangest thing is in multiplayer mode, some players get all the texts but others do not. I do not know if it will be a script problem or it is a bug from the same server. In my case, the problem is in SP and MP.

 PD: My screen resolution is 1680x1050 (16:10) In case the error is product of the resolution of screen.

Photo, Issue vehicles description: http://photobucket.com/gallery/user/TteMerino/media/bWVkaWFJZDoxNTQ1MTg5Mjc=/?ref=1

Photo, Issue text admin panel: http://photobucket.com/gallery/user/TteMerino/media/bWVkaWFJZDoxNTQ1MTg5Mjg=/?ref=1

Photo, issue, does not show the price: http://photobucket.com/gallery/user/TteMerino/media/bWVkaWFJZDoxNTQ1MTg5Mjk=/?ref=1

**Comment by Ppgtjmad** [comment]
Hello,

Let me tell you that you're missing localized text located in **stringtable.xml**, you probably forgot to merge it with yours (if you had one already) or to copy over, see -> https://github.com/Ppgtjmad/SimpleShops/wiki/How-to-use-it-in-your-custom-mission

This will solve your problem.

**Comment by TteMerino** [comment]
I create a single mission with the [HG] files and I have the same problem.
photo, the same problem with [HG] original files: https://ibb.co/h2iWZk

PD: My custom mission have the stringtable.xml file, i launch the mission in my server and to some players shows the texts. https://ibb.co/mG560Q

**Comment by TteMerino** [comment]
I found the problem, the mod does not accept another language of game that is not English. Players who have "Weapon 3" in English works all the texts, those who have it in Spanish, does not get the texts.

**Comment by Ppgtjmad** [comment]
Yeah because I don't know spanish guys, so can you translate stringtable.xml into spanish for me and I'll add it to the mission files ok?

**Comment by TteMerino** [comment]
Sure, i can translate the file, in this case, spanish and english player could they play with all the texts?

**Comment by TteMerino** [comment]
Here I have the translation to Spanish, I would like to translate the ranges that appear in the HUD, in what file can I do that? http://www.mediafire.com/file/td03kyto6y9fwyy/translation+to+Spanish+by+Merino%5BBSA%5D.zip

**Comment by Ppgtjmad** [comment]
Hello,

Thanks a lot, I updated repo with new stringtable.xml & localized ranks in HUD & tags.

https://github.com/Ppgtjmad/SimpleShops/commit/95d28a4efba187dc71b7c1518290a2760a0ff3f6
