### ISSUE TITLE
How does respawn work?

### ISSUE THREAD

**Issue by TteMerino** [Ppgtjmad/SimpleShops#24]
I think it is with some "makers" but technically how they would be placed in the editor?

**Comment by Ppgtjmad** [comment]
Hello,

There is no respawn system, only couple of things to check and/or reset when a player respawns (see fn_respawn.sqf).

**Comment by TteMerino** [comment]
But is there any way to place a respawn for each faction?

**Comment by Asmodeuz** [comment]
TteMerino, I think you will be better off with using the available Multiplayer modules provided by Arma 3 at least if you are looking for multiplayer respawn positions for human players.

Go in the in-game editor and familiarize yourself with Systems -> Modules -> Multiplayer and place a _Respawn position_ for example.

**Comment by TteMerino** [comment]
I understand, I did that but when a player dies the "give money" option does not appear.

**Comment by TteMerino** [comment]
This error is the one that appeared when reappearing  https://ibb.co/gnxsH5

**Comment by TteMerino** [comment]
I found the error, they can close the subject
