### ISSUE TITLE
Driver of a vehicle multicrewed by human players doesn't get rewards and penalties for killing friendly and enemy soldiers by driving over them

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#25]
The changes made in the code (see: [**fn_aiUnitSetup.sqf**](https://github.com/Ppgtjmad/SimpleShops/commit/524a87571f9f581edfc1767a04bc67a3d653fcfc#diff-d63dafa9a84b7e9dd2896fbb96e5f1a0) and [**fn_killed.sqf**](https://github.com/Ppgtjmad/SimpleShops/commit/524a87571f9f581edfc1767a04bc67a3d653fcfc#diff-32c7ac4918db84ab0dd9a20cc02ee35b) )  to target the issue https://github.com/Ppgtjmad/SimpleShops/issues/22 affected the reward/penalty dealing behaviour in a way that the **driver** of a vehicle multicrewed by human players doesn't anymore receive rewards or penalties for driving over (and thus killing) friendly/enemy soldiers.

Though less crucial as an issue I'm adding this in the hopes that this behaviour could somehow be fixed with a certain EventHandler or some other way in the future.

**Comment by Ppgtjmad** [comment]
Am on it :)
