### ISSUE TITLE
XP bar in mod shows "Scalar NaN" when I use it in a Multiplayer server. How to fix?

### ISSUE THREAD

**Issue by DeusMaveriX** [Ppgtjmad/SimpleShops#27]
might have something to do with fn_isNumeric.sqf

**Comment by DeusMaveriX** [comment]
might have something to do with fn_isNumeric.sqf

**Comment by DeusMaveriX** [comment]
Also, is there any way to retain mod functionality when loading a save in a scenario? Many mods seem to stop working when I load a save after dying.

**Comment by Ppgtjmad** [comment]
I think your issue is fixed (contacted on Steam), closing ticket.
