### ISSUE TITLE
Petition

### ISSUE THREAD

**Issue by TteMerino** [Ppgtjmad/SimpleShops#29]
Hi, your mod is very good, I use it in many roleplay missions modifying some parameters. As this mod is about "Stores", could there be a way to "sell" your items in the same Store?. I'm looking for a way to create specialized stores so that, for example, players take out apples and sell them in the store. I am aware of the comments. Thx.

**Comment by Ppgtjmad** [comment]
Hello,

Should be done by the end of the week.

**Comment by TteMerino** [comment]
Oh, great, Thanks you.

**Comment by Ppgtjmad** [comment]
And here it goes -> https://github.com/Ppgtjmad/SimpleShops/commit/d66501b7695e5183c28f9d049a57f9f2ee25f2f0

**Comment by TteMerino** [comment]
Thank you very much for your work. The last thing I wanted to ask you. I'm looking for a way to a player to sell his vehicle. The other thing, that a player can pass the keys of his vehicle to another person. I insist that your work is fabulous.

**Comment by Ppgtjmad** [comment]
Ok ok I'll see what I can do :)

**Comment by Ppgtjmad** [comment]
Your dreams come true -> https://github.com/Ppgtjmad/SimpleShops/commit/fa1f5d379a69d4e0d25aef45bc1f559b010f6783

**Comment by TteMerino** [comment]
Thx, you are amazing. Good work.
