### ISSUE TITLE
Kill rewards

### ISSUE THREAD

**Issue by ABurnes** [Ppgtjmad/SimpleShops#30]
I trying ur script for mission for my zombie survival game mode im using Ravage mod but i cant get rewards or xp when i kill zombies or AI bandits

**Comment by Ppgtjmad** [comment]
Hello,

Make sure you read this -> https://github.com/Ppgtjmad/SimpleShops/wiki/How-to-setup-kill-rewards

**Comment by Ppgtjmad** [comment]
Its been 17 days now, closing it, re-open if needed.
