### ISSUE TITLE
[Question] Remapping ATM object

### ISSUE THREAD

**Issue by logimy** [Ppgtjmad/SimpleShops#31]
Hello there! 
Thank you for awesome framework, i love how it works. Just a simple question around here. 
**Where can i remap the ATM object?** 
From `Land_Atm_01_F` and `Land_Atm_02_F` to something else? 

**So, what i have done for this moment:**
I'm already reached the goal by using a quickhack: `atm_var_name hideObject true; `, but i'm interested in normal methods of remapping ATM object. Searching for `Land_Atm_01_F` in whole HG folder doesn't give any results, so now i'm asking you here.

**Comment by Ppgtjmad** [comment]
Hello, you again?

Check this file
```HG/Functions/Client/Generic/fn_nearbyATM.sqf```
 
Here I think you can figure out how to do it.

If your ATMs have classnames it's really easy, open 
```HG/Functions/Client/EVH/fn_keyDown.sqf```

Find the ATM key and add a check here for your classname.

**Comment by logimy** [comment]
Quickhack addition: it's important to ATM varname was starting (or just contain, i'm not sure) with `atm_`. 

Example:  
ATM variable name: `atm_monk`
`atm_monk hideObjectGlobal true;`

**Comment by logimy** [comment]
Yeah, i find the way, thanks. 
I just need to add `atm_` to the start of each ATM object variable name.
**Thank you!**
