### ISSUE TITLE
Partially full (or completely empty) magazine/clip that is attached to a gun gets refilled when accessing Gear Shop

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#32]
Any only partially full magazine/clip that is attached to a weapon gets filled to full when player enters Gear Shop.

How to test:
use the Simple Shops VR test mission and create a multiplayer session for it either through the in-game editor or use a dedicated server. Also: test with vanilla Arma 3 and the latest version of Simple Shops.

Enter the test mission and after spawning empty the pistol or main weapon magazine or the magazines of both available weapons by firing the guns.
Without reloading a new magazine into either of the guns

- access Gear Shop and close it without otherwise using the shop
- observe that the magazines that were emptied just earlier are full again

**Comment by Ppgtjmad** [comment]
Hello,

Can you check now? https://github.com/Ppgtjmad/SimpleShops/commit/41e15a698606d9a13ae6e844e90ac3873d93f4bc

**Comment by Asmodeuz** [comment]
Here are some observations from testing the latest commit:

how the functionality now works is that the (partially full or completely empty) magazine that is attached to the weapon at the time of entering>exiting Gear Shop gets moved into the player's inventory.
This magazine will then be replaced by a full magazine that is attached to the weapon.

The empty/partially full magazines don't stack up in player's inventory: if such magazine is already present in the inventory it will be replaced with another of the same kind. This means that coupled with the weapon receiving always a new full magazine there is no possibility for the player to run out of ammo.

I faced some difficulties in phrasing my words with the current functionality and how I'm now explaining them might come out completely wrong. Sp please feel free to contact me via Steam or Discord and/or consider joining my test server to test this one out.
