### ISSUE TITLE
Script errors out with custom gear

### ISSUE THREAD

**Issue by Eogos** [Ppgtjmad/SimpleShops#34]
So I tried to setup a custom set of gear for an ambient mission I'm making but anytime I modify the HG_GearShopCfg.h file from the default it throws an error on loading, an error on trying to open gear shop (and failing), and then an error upon returning to editor.

Screenshots of the errors: https://imgur.com/a/IkVAX

The third error always say the same thing regardless of what is in line 20

Here is a gist of my gear config setup: https://gist.github.com/Eogos/5b1e9e8eabab115254a683cfcce1ff7a

Nothing else in the script has been modified from default as of yet. Am I doing something wrong or has something completely broke here?

**Comment by Eogos** [comment]
oh also here is all the mods active:
- https://gsca3.com/repos/MainOps/
- Hindu Kush
- Hindu Kush lighting fix
(obviously not all are used in the script right now but I thought it'd still be important to note all mods loaded)

**Comment by Eogos** [comment]
NEVER MIND, I'M JUST A FUCKING IDIOT WHO WASTED MULTIPLE HOURS CAUSE HE FORGOT A BUNCH OF COMMAS.

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

(I'm very upset with myself right now)

**Comment by Eogos** [comment]
Never mind it's still happening but now it says line 84.

new gist of config: https://gist.github.com/Eogos/5e631a0ce3082f088bd9dfd13877c474

**Comment by Eogos** [comment]
annnnnnnnnnd I'd missed another comma. I wanna kms. Please send rubber duck and a seeing dog.

**Comment by Ppgtjmad** [comment]
Please provide your address and I shall send those to you :)
