### ISSUE TITLE
[Feature Request] Claiming Unowned Vehicles

### ISSUE THREAD

**Issue by Eogos** [Ppgtjmad/SimpleShops#35]
So in the mission I'm creating with your script in it, the players are insurgents during the soviet-afghan and therefore don't have the most top end equipment, even what they can buy only goes so far and because of this I'm planning on encouraging them to steal enemy equipment and by extension their vehicles as well. 

However there currently isn't anyway of "claiming" an unowned vehicle that was either spawned from Zeus, Editor, or ALiVE so the idea of stealing vehicles kind of loses it's purpose since other players can just take their vehicle and they lose the vehicle upon any server restart or mission change. If possible it'd be nice if there was some kind of way of claiming a vehicle, either by driving it to the storage point for the garage or just some kind of addAction that allows you to set the vehicle as owned by you.

**Comment by Ppgtjmad** [comment]
I heard your prayers :)

**Comment by Eogos** [comment]
Nice, I'll give it a try later this week
