### ISSUE TITLE
Profile Kit Persistance Stopped Working

### ISSUE THREAD

**Issue by Eogos** [Ppgtjmad/SimpleShops#36]
Hello, it's me again. So this time, after I've finally got all the items, weapons, gear, vehicles, etc. I wanted added to all the shops I ran into a new problem. While in the middle of finishing up adding some items the kit persistence stopped working. My rank, XP, kills, and money all continued to be saved but my outfit, inventory, and guns never would. No script error is thrown so I can't tell what's causing it. The vehicles seem to also be a little finicky sometimes they save and sometimes they don't. Any ideas? (I made sure to have other people look over it this time too, so hopefully it isn't something stupid like a missing comma)

My config settings and RPT file: https://www.dropbox.com/sh/4mtxd945x6jqy0e/AACqTzvHOfMUCRg6K58Lo-E0a?dl=0

List of loaded mods:
- https://gsca3.com/repos/MainOps/
- HinduKush
- HinduKush lighting fix

**Comment by Ppgtjmad** [comment]
Hello,

I couldn't reproduce the issue you're having so I put this ticket on hold, double check if it is not on your side. Thank you.

**Comment by Eogos** [comment]
Alright, thank you for helping, I'll see if I can't fix it myself.

**Comment by Eogos** [comment]
Seems like the script just doesn't like certain classnames of objects. One example being the civilian Ural from CUP. Putting it in the vehicle shop will break the persistence for player kits for whatever reason but if I go and grab the same ural but from another another faction, like the CUP Russian Federation, it works despite the only difference being a different classname to get a different default skin.

Either way, looks like I'll just have to go one by one and find all the stuff it doesn't like for whatever reason.
