### ISSUE TITLE
my car Inventory empty. fn_setinventory.sqf 17line??

### ISSUE THREAD

**Issue by eroticcrow** [Ppgtjmad/SimpleShops#37]
use extDB3

my car inventory empty.

After putting an item in my car inventory, if you spawn the vehicle again, the items will disappear from the inventory.
It seems to be a problem in the process of loading the db.

plz check 

 "fn_setinventory.sqf" 17line
 "format["SELECT Inventory FROM HG_Vehicles WHERE WHERE  PID =  <-

HG_Vehicles WHERE WHERE PID ?? or HG_Vehicles WHERE PID 

I modified both of them. But it does not work.

**Comment by Ppgtjmad** [comment]
Hello,

Yes my bad there was two WHERE... remove one and should be good.

**Comment by Ppgtjmad** [comment]
Related to this https://github.com/Ppgtjmad/SimpleShops/issues/39, closing.
