### ISSUE TITLE
Weapon muzzle flash can be seen when using clothing shop

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#4]
This is an interesting one and not necessarily in the highest of priorities.

When a human player is using clothing shop no other alive human players can be seen moving around no matter how close or far they happen to be.

But when one of these human players happen to fire their weapon the weapons muzzle flash can be observed by the player that is using the clothing shop.

**Comment by Ppgtjmad** [comment]
> When a human player is using clothing shop no other alive human players can be seen moving around no matter how close or far they happen to be.

Yup exactly how it's meant to be.

> But when one of these human players happen to fire their weapon the weapons muzzle flash can be observed by the player that is using the clothing shop.

As stated in BIKI (https://community.bistudio.com/wiki/hideObject)

> This command will hide a unit, but he will still shoot enemies. Unit will be invisible, but weapon muzzle are visible.

There are workarounds:
- Teleport player in air
- Teleport player to somewhere safe (maybe make use of a safe point marker)

What do you think is best?

**Comment by Asmodeuz** [comment]
We put some thought on this with a friend of mine and sort of thought about the first choice _Teleport player in air_

But come to think of it: could hiding of a unit be made toggleable? Am I right that for players to choose clothing uninterrupted you chose to hide other players expect the one using the shop?
When making missions using your shop system I'd rather see the other players but place the shop itself so that other players wouldn't obstruct the one player using the clothing shop with their presence.

**Comment by Ppgtjmad** [comment]
> Am I right that for players to choose clothing uninterrupted you chose to hide other players expect the one using the shop?

Yes you're right. I did that so no players can troll you when in shop (blocking view).

> When making missions using your shop system I'd rather see the other players but place the shop itself so that other players wouldn't obstruct the one player using the clothing shop with their presence.

Yeah but not everyone will think about that you know, hence why I set it up so no-one can obstruct your view. But I think am gonna get rid of it completely. 

After all BIS_fnc_virtualArsenal doesn't hide anything! Hehe.

**Comment by Asmodeuz** [comment]
We did test this and can confirm that the player that is using the clothing shop can see other players around now.

So fix'd..or should I say chang'd!
