### ISSUE TITLE
Other currencies

### ISSUE THREAD

**Issue by Sikksens** [Ppgtjmad/SimpleShops#43]
Hey there,

Just want to check if other currencies are supported atm, I'm wanting to use Rubles and have tried both ISO formats of "RUB" and "RUR" but just end up getting the amount without a currency prefix.

**Comment by Ppgtjmad** [comment]
Hi @Sikksens 

I'm so sorry, this ticket is so old... my bad...

`[500,true,"RUB"] call HG_fnc_currencyToText` 

should give you ₽500.
