### ISSUE TITLE
Reward for winners' side?

### ISSUE THREAD

**Issue by ErogeXiao** [Ppgtjmad/SimpleShops#44]
I'm making a sector control mission with SimpleShops, and when one of the sides lose all their respawn tickets the other one just win without any award. I'm wondering how can I add the reward for the winners' team?

**Comment by Ppgtjmad** [comment]
Hello,
What kind of reward? Money, XP? Both? You have all the functions you need in the wiki under "Useful Functions".

**Comment by Ppgtjmad** [comment]
No feedback from user, closing.
