### ISSUE TITLE
How to add items that the trader will buy?

### ISSUE THREAD

**Issue by 0ozymandias** [Ppgtjmad/SimpleShops#45]
Sorry if this is annoying; but how would you be able to add items that the trader would buy? I added some items to HG_TradersCfg.h yet there are unable to be sold to the trader, even items that were in the list, save for the map, could not be sold.

**Comment by Ppgtjmad** [comment]
Hello, 
Can you please copy & paste your tradersconfig file here?

**Comment by 0ozymandias** [comment]
Aha! Nevermind, I realized that I had kept "true" inside the items that he would buy, now it works without issue. Thank you!
