### ISSUE TITLE
ATM doesn't work

### ISSUE THREAD

**Issue by marin0s** [Ppgtjmad/SimpleShops#46]
Hi,
I have place a ATM on Chernarus, and name it "atm_01" but it doesn't work.
The ATM is enable in HG_Config.h file.
Can you help me ?
Thanks ! :-)

**Comment by Ppgtjmad** [comment]
Hello,

Make sure you're pushing the right key on your keyboard when you're close to your ATM.
Double check HG_Configh line 103 **atmKey** default is 0x14 which is T.

**Comment by marin0s** [comment]
Hello
Thank you for your answer. Yes it was the T key that I did not find!
Do you know if it is possible to add a "Addaction" to access the ATM with the mouse wheel?

**Comment by Ppgtjmad** [comment]
Hello,

Here you go (put this in init box):

`this addAction["<img image='HG\UI\Icons\bank.paa' size='1.5'/><t color='#FF0000'>Open ATM</t>",{_this call HG_fnc_dialogOnLoadATM},"",0,false,false,"",'(alive player) && !dialog && player distance _target < 3'];`

**Comment by marin0s** [comment]
Oh great ! Thanks you ! :)
