### ISSUE TITLE
spawn position got way off from the marker if the markers is inside the object

### ISSUE THREAD

**Issue by Heinz132** [Ppgtjmad/SimpleShops#49]
hello, im attempting to make the custom garage which i placed from the editor

i placed the platform on the ground for a stable floor and put the hanger on it and put two marker inside the hanger

but when i spawn the vehicle, it spawned way far off from the markers and collide with the hanger's wall and explode

i tried to change [_classname,_sp,[],0,"NONE"] to [_classname,_sp,[],0,"CAN_COLLIDE"] in the spawnvehicle.sqf but it still keeps spawning at wrong position

advice needed

**Comment by Ppgtjmad** [comment]
Hi there,

In the same file, line 46:

Change 
`_vehicle = _classname createVehicle (markerPos _sp);`

To

`_vehicle = createVehicle [_classname,(markerPos _sp),[],0,"CAN_COLLIDE"];`

The line you modified is for when the passed position is this format [0,0,0] but since you use markers the passed position is a string (marker name) so the else statement kicks in.

**Comment by Heinz132** [comment]
Thanks for the advice! now it's spawning at the right position

i got some more question,

Q1. is it available to use multiple markers as the store point for a single garage?
ex) if 1 is in the use, you drive the vehicle to 2 and store it.

this is my config

```
class Aircraft_Garage
{
    conditionToAccess = "true";
    allowedTypes[] = {"Air"};
	spawnPoints[] =
	{
		{"A1",{"A1"}},
		{"A2",{"A2"}}
	};
	storePoint = "A1"="A2"="A3"="A4"
};
```
i tried 3 kinds,
A.`storepoint = "A1","A2","A3","A4"` 
B.`storepoint[] = {AircraftStore{"A1","A2","A3","A4"};`
C.`storepoint = "A1"="A2"="A3"="A4"`

A. cause the error `',' encountered instead of '='`

B. no errors but it can't detect the vehicles on it

C. only A1 gets active as the store point and others are not

is there any solution to use multiple garage points?



Q2. can i use the custom Vehicle Type?

ex) separate Air to 3 kinds (helicopters,jets,UAV) and assign to each 3 Hangers at difference location

i made a Landing site structure for heli's which designed for only heli's, but if i ues `allowedType = Air`, jets are in the same list and get accidentally spawned and get stuck.

so i want to separate the vehicle types more detailed

is it possible to do it?

found the fn_getType.sqf but i have no idea how to edit this one.


Q3. automatically rewarded when Task is completed?

im trying to combine with Ghost Enemy Assault, it creates several task randomly

so if the task is completed, i want to give all players a reward.

is it available? please advice.
