### ISSUE TITLE
No reward with ACE

### ISSUE THREAD

**Issue by redeye83** [Ppgtjmad/SimpleShops#5]
When this is used on a server running ACE there is no reward as the damage is handled by ACE and each "kill" acts like "suicide".

**Comment by Ppgtjmad** [comment]
Hello,

Unfortunately I don't know ACE3 (never used it) so it will be hard for me to help you, they probably have their own EVHs that you can somehow override.

I wish I could help, if you know how ACE works let me know and I'll adapt the code for it.

**Comment by redeye83** [comment]
I know it does have its own EVHs but sadly I dont know where there are or how they work. ACE messes up alot of stuff sadly

**Comment by Ppgtjmad** [comment]
Am closing this since it's not related to the shops. Hope you get this one fixed...
