### ISSUE TITLE
Set others data

### ISSUE THREAD

**Issue by nanhu888** [Ppgtjmad/SimpleShops#51]
How to set the data of other players in multiplayer mode?

**Comment by Ppgtjmad** [comment]
Hello,

If the **savingMethod** is set to **"profile"** there is actually no way to manage players data in game, I am thinking about making a dialog that will serve this purpose.
Other than that, there are multiple functions that you can execute remotely on the player of your choice https://github.com/Ppgtjmad/SimpleShops/wiki/Useful-Functions 

Thanks for using my shops!
