### ISSUE TITLE
About data storage

### ISSUE THREAD

**Issue by nanhu888** [Ppgtjmad/SimpleShops#52]
Is it possible to set up a player-specific item box that can also be saved as the player's data?

**Comment by nanhu888** [comment]
I have an idea: set up a storage box, and this storage box is synchronized with the data (extdb3), and the player can put the items or weapons that they want to sell but have no place for the backpack into the storage box, so as to achieve the player Will you worry about your equipment disappearing when you are offline?

**Comment by nanhu888** [comment]
Can this project be done?

**Comment by Ppgtjmad** [comment]
@nanhu888 

Hi, I need a more elaborated breakdown of your idea, as in logical steps so I may come up with the required code.

**Comment by Ppgtjmad** [comment]
No feedback from user, closing.
