### ISSUE TITLE
Question about the virtual garage "addaction"

### ISSUE THREAD

**Issue by BrianV1981** [Ppgtjmad/SimpleShops#54]
Hello, 

First, I want to thank you for sharing your scripts! Second, I would like to say that I am not a scripter by any stretch of the imagination, so if I ask something that doesn't make sense, I apologize.

I am trying to integrate the ace interaction menu with the HG virtual garage. I am trying to figure out what exactly needs to be called? I will post what I have and it should give you an idea where I am going with this. 

In your wikis [Usage](https://github.com/Ppgtjmad/SimpleShops/wiki/Usage) page there is some code to addAction to an object to create a virtual garage.

```
this addAction["<img image='HG\UI\Icons\garage.paa' size='1.5'/><t color='#FF0000'>"+(localize "STR_HG_GARAGE")+"</t>",{_this call HG_fnc_dialogOnLoadGarage},"HG_DefaultGarage",0,false,false,"",'(alive player) && !dialog && player distance _target < 3'];
this addAction["<img image='HG\UI\Icons\garage.paa' size='1.5'/><t color='#FF0000'>"+(localize "STR_HG_GARAGE_PARK")+"</t>",{_this call HG_fnc_storeVehicleClient},"HG_DefaultGarage",0,false,false,"",'(alive player) && !dialog && player distance _target < 3'];
```

So, I came up with

```
customaction = ['CustomAction 1','Garage','','',{true}] call ace_interact_menu_fnc_createAction;
[player, 0, ["ACE_MainActions"], customaction] call ace_interact_menu_fnc_addActionToObject;

customaction = ['CustomAction 2','Open Garage Menu','',{_this call HG_fnc_dialogOnLoadGarage},{true}] call ace_interact_menu_fnc_createAction;
[player, 0, ["ACE_MainActions","CustomAction 1"], customaction] call ace_interact_menu_fnc_addActionToObject;
customaction = ['CustomAction 3','Store Vehicle','',{_this call HG_fnc_storeVehicleClient},{true}] call ace_interact_menu_fnc_createAction;
[player, 0, ["ACE_MainActions","CustomAction 1"], customaction] call ace_interact_menu_fnc_addActionToObject;
```

I found that calling `_this call HG_fnc_storeVehicleClient` will open the garage menu, but it is not the actual garage, but only the interface. Similarly, when calling `_this call HG_fnc_storeVehicleClient` it shoots me an error and a hint that there is no owned vehicle on the store point. 

Any help would be greatly appreciated,
Brian V.

**Comment by Ppgtjmad** [comment]
Hi,

I'm not familiar with ace framework so I've just read their wiki (https://ace3mod.com/wiki/framework/interactionMenu-framework.html)

ace_interact_menu_fnc_createAction
```
* Argument:
* 0: Action name <STRING>
* 1: Name of the action shown in the menu <STRING>
* 2: Icon <STRING>
* 3: Statement <CODE>
* 4: Condition <CODE>
* 5: Insert children code <CODE> (Optional)
* 6: Action parameters <ANY> (Optional)
* 7: Position (Position array, Position code or Selection Name) <ARRAY>, <CODE> or <STRING> (Optional)
* 8: Distance <NUMBER> (Optional)
* 9: Other parameters [showDisabled,enableInside,canCollapse,runOnHover,doNotCheckLOS] <ARRAY> (Optional)
* 10: Modifier function <CODE> (Optional)
```

ace_interact_menu_fnc_addActionToObject
```
* Argument:
* 0: Object the action should be assigned to <OBJECT>
* 1: Type of action, 0 for actions, 1 for self-actions <NUMBER>
* 2: Parent path of the new action <ARRAY> (Example: `["ACE_SelfActions", "ACE_Equipment"]`)
* 3: Action <ARRAY>
```

This code in the init box:

```
act_0 = [(localize "STR_HG_GARAGE"),(localize "STR_HG_GARAGE"),"HG\UI\Icons\garage.paa",{["HG_DefaultGarage"] call HG_fnc_dialogOnLoadGarage},{(alive player) && !dialog},{},[],[],3] call ace_interact_menu_fnc_createAction;
[this,0,["ACE_MainActions"],act_0] call ace_interact_menu_fnc_addActionToObject;

act_0 = [(localize "STR_HG_GARAGE_PARK"),(localize "STR_HG_GARAGE_PARK"),"HG\UI\Icons\garage.paa",{["HG_DefaultGarage"] call HG_fnc_storeVehicleClient},{(alive player) && !dialog},{},[],[],3] call ace_interact_menu_fnc_createAction;
[this,0,["ACE_MainActions"],act_0] call ace_interact_menu_fnc_addActionToObject;

act_0 = nil;
```

Or name the object, remove my addActions and add this code in your initPlayerLocal.sqf

Let's say the object is named **myObject**

```
private _act = [(localize "STR_HG_GARAGE"),(localize "STR_HG_GARAGE"),"HG\UI\Icons\garage.paa",{["HG_DefaultGarage"] call HG_fnc_dialogOnLoadGarage},{(alive player) && !dialog},{},[],[],3] call ace_interact_menu_fnc_createAction;
[myObject,0,["ACE_MainActions"],_act] call ace_interact_menu_fnc_addActionToObject;

_act = [(localize "STR_HG_GARAGE_PARK"),(localize "STR_HG_GARAGE_PARK"),"HG\UI\Icons\garage.paa",{["HG_DefaultGarage"] call HG_fnc_storeVehicleClient},{(alive player) && !dialog},{},[],[],3] call ace_interact_menu_fnc_createAction;
[myObject,0,["ACE_MainActions"],_act] call ace_interact_menu_fnc_addActionToObject;
```

**Comment by BrianV1981** [comment]
Hello,
Thank you for taking the time to look into this. However, I am still ending up with the same outcome. The interface opens, but the garage is empty and I am unable to select a spawn point. 

![20200729211618_1](https://user-images.githubusercontent.com/48861936/88927381-504cac80-d245-11ea-9bb6-f84e163d909e.jpg)

Here is a screenshot of what vehicles should be showing up in the garage. You will also notice the spawn point selection is available.

![20200729211635_1](https://user-images.githubusercontent.com/48861936/88927554-96a20b80-d245-11ea-94fd-f33a495f5201.jpg)


I am also unable to store vehicles with the new code. However, this does pop an error. This error does not happen when utilizing your normal garage addAction code when storing vehicles.

```
20:45:10 Error in expression <s = markerPos _storePoint;
};

_near = (nearestObjects [_pos,_allowedTypes,30]) >
20:45:10   Error position: <nearestObjects [_pos,_allowedTypes,30]) >
20:45:10   Error 0 elements provided, 3 expected
20:45:10 File HG\Functions\Client\Garage\fn_storeVehicleClient.sqf [HG_fnc_storeVehicleClient]..., line 173
20:45:15 "FIXME: Possible empty string. Content: "
20:45:29 "FIXME: Possible empty string. Content: "
20:45:41 Error in expression <s = markerPos _storePoint;
};

_near = (nearestObjects [_pos,_allowedTypes,30]) >
20:45:41   Error position: <nearestObjects [_pos,_allowedTypes,30]) >
20:45:41   Error 0 elements provided, 3 expected
20:45:41 File HG\Functions\Client\Garage\fn_storeVehicleClient.sqf [HG_fnc_storeVehicleClient]..., line 173
```

Again, thank you for taking the time to look into this. Any help is appreciated. 

Regards,
Brian V.

**Comment by Ppgtjmad** [comment]
Open both 
HG\Functions\Client\Garage\fn_dialogOnLoadGarage.sqf 
HG\Functions\Client\Garage\fn_storeVehicleClient.sqf

Replace
`params["_target","_caller","_id","_garage"];`
With
`params["_garage"];`
