### ISSUE TITLE
Suggestion: Add "Virtual Barracks"

### ISSUE THREAD

**Issue by BrianV1981** [Ppgtjmad/SimpleShops#55]
Hello,
I wanted to post a suggestion that I think some people may be interested in. A virtual barracks, identical to your garage system, but for AI units that are in the player's group. 

Regards,
Brian

**Comment by Ppgtjmad** [comment]
I'll make it that you can recruit AI units from the dialog with money.

The system will use a config file where you can make different kind of units with the gear of your choice. 

These units will then be available for purchase.

**Comment by Ppgtjmad** [comment]
I'll see what I can do, for now here's the units shop -> https://github.com/Ppgtjmad/SimpleShops/commit/1af64c6870a4e555d9a1bb1071edcdf4c629bed7
