### ISSUE TITLE
Problems with item shop

### ISSUE THREAD

**Issue by Skyrbose** [Ppgtjmad/SimpleShops#57]
I tried to use items like Apersmine or ace_morphineitem the shop sell it to me, but dont give me any item, only takes the money

**Comment by Ppgtjmad** [comment]
Hi @Skyrbose 

ace_moprhineitem should be ACE_morphine
and
Apersmine is the actual mine, the item is APERSMineDispenser_Mag and APERSTripMine_Wire_Mag
