### ISSUE TITLE
Vehicle still on garage

### ISSUE THREAD

**Issue by Skyrbose** [Ppgtjmad/SimpleShops#58]
When a vehicle is destroy or deleted and them the server restart the vehicle is back on the garage. How can i change that? Not a clue in config files

**Comment by Ppgtjmad** [comment]
There's nothing you can do right now, but I'm on it.

**Comment by Ppgtjmad** [comment]
Here it is -> 8f22767d9f0bbde21bf0bfbdf3e7b0238458d0ed

**Comment by Skyrbose** [comment]
Oh, thanks a lot!

I have another posible enhancement, cleanup the inventory of the vehicle when u buy it, sometines it came with stuff of the vehicle and is a little bit annoying to take off the users

**Comment by Ppgtjmad** [comment]
In **HG_Config.h** you have to set **clearInventory** to true

**Comment by Skyrbose** [comment]
But that clear all the inventory in every restart

**Comment by Ppgtjmad** [comment]
That clear vehicles inventory when they're spawned, this parameter is used in HG\Functions\Server\fn_spawnVehicle.sqf

**Comment by Skyrbose** [comment]
Ill try it, but im testing the cleanup of the vehicles when it gets destroy and dont works, even with the download of your script in vanilla with no modifications

**Comment by Ppgtjmad** [comment]
Should be fixed now -> 8461aa2279f9a04ef6ce862cbe378c4a007f2f44

**Comment by Skyrbose** [comment]
Done, thanks!
