### ISSUE TITLE
Lag spikes after last update

### ISSUE THREAD

**Issue by BrianV1981** [Ppgtjmad/SimpleShops#59]
Hello,
I am experiencing lag spikes every second or so ever since this last update. Prior to this update, I didn't experience any issues like this.

Regards,
Brian

**Comment by Ppgtjmad** [comment]
@BrianV1981 

I have not noticed any lag spikes since the last update, make sure the cleanup time is not set too low (< 1 min).
Check your RPTs for clues. Report back.

**Comment by Ppgtjmad** [comment]
No feedback from user, closing.

**Comment by Ppgtjmad** [comment]
e3dd121 should fix the issue while keeping the cleanup active.

**Comment by Ppgtjmad** [comment]
Got enough feedback to know that the issue is fixed, closing.
