### ISSUE TITLE
call HG_fnc_addOrSubCash working on editor hosted MP but not on dedicated server

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#6]
As per recommandations here (https://forums.bistudio.com/topic/187814-release-simple-weapon-shop-system/?page=5#comment-3162533) I did a test with **[500,0] call HG_fnc_addOrSubCash**. I placed that function in one of the Sector module's _Expression_-field and got few different results depending what approach I was using. See picture for reference about Sector module settings: http://i1370.photobucket.com/albums/ag278/testusah123/sectorExpressionAddCash_zpsonkzp47w.jpg

1) if _enableSave_ is set to **true** in HG_Config.h and when hosting a multiplayer game from the mission editor the player that captures the sector gets the set reward (in this case 500)

2)  if _enableSave_ is set to **false** in HG_Config.h and when hosting a multiplayer game from the mission editor an error gets displayed immediately when the mission begins (the player spawns in the first time). Didn't happen to take a screenshot of the error this time.

3) if the mission is placed in a dedicated server and played from there an error gets displayed immediately when the mission begins and every time when capture of a sector happens. There is no difference if _enableSave_ is set to **false** or **true** in HG_Config.h. Also the player capturing the sector doesn't receive any reward. 
Here's the error for case 3.

```
21:51:27 Error in expression <switch(_mode) do
{
case 0:
{
_newVal = _oldVal + _amount;
};
case 1:
{
_newVal >
21:51:27   Error position: <_oldVal + _amount;
};
case 1:
{
_newVal >
21:51:27   Error Undefined variable in expression: _oldval
21:51:27 File mpmissions\__cur_mp.VR\HG\Functions\Generic\fn_addOrSubCash.sqf, line 22
21:51:27 Error in expression <
profileNamespace setVariable["HG_Save",_newVal];
saveProfileNamespace;
} else {>
21:51:27   Error position: <_newVal];
saveProfileNamespace;
} else {>
21:51:27   Error Undefined variable in expression: _newval
21:51:27 File mpmissions\__cur_mp.VR\HG\Functions\Generic\fn_addOrSubCash.sqf, line 32
21:51:27 Error in expression <layCtrl 8000) ctrlSetText format["%1",([_cash] call BIS_fnc_numberText)];
};

ca>
21:51:27   Error position: <_cash] call BIS_fnc_numberText)];
};

ca>
21:51:27   Error Undefined variable in expression: _cash
21:51:27 File mpmissions\__cur_mp.VR\HG\Functions\HUD\fn_HUD.sqf, line 27
```

**Comment by Ppgtjmad** [comment]
Hey,

Try this in expression field:

``
if ((_this select 1) != sideUnknown) then {[500,0] call HG_fnc_addOrSubCash}
``

Thing is that the trigger is fired when mission starts, when you host locally it it's not a problem but when in dedicated environment it is because player doesn't exist thus throwing an error saying undefined blabla which is true.

So above is the way to stop the trigger from triggering. Report back when possible.

**Comment by Asmodeuz** [comment]
Hey,

thank You for the suggestion.

We ran some tests and as you presumed using that snippet stops the error from appearing when the mission begins.

The error now appears only when a player captures the sector and probably because of that capturing the sector still doesn't yield any reward for the player.

**Comment by Ppgtjmad** [comment]
My best bet would be to use

``
[500,0] remoteExecCall ["HG_fnc_addOrSubCash",(_this select 1),false]
``

instead of

``
[500,0] call HG_fnc_addOrSubCash
``

That will reward all team members for the sector capture.

**Comment by Asmodeuz** [comment]
> My best bet would be to use
> 
> [500,0] remoteExecCall ["HG_fnc_addOrSubCash",(_this select 1),false]

That worked like a charm! Just like you said it did reward all players of the same side and we did a test to be sure that it wouldn't reward "enemies" in cases such as OPFOR captures an objective and it would reward also BLUFOR players. Luckily it didn't!

I'd say this issue is drawing to a close but just before that (mainly because as far as I see it this would anyway come up sooner or later):
can you already see within your mind or your soul that how much expanding would that simple snippet need that it would only provide rewards to the players that actually are inside the capture area?
Would it need a helluva lot more changes or changing completely to some other approach?

**Comment by Ppgtjmad** [comment]
Hey,

Sorry for the late replay.

So to do this:

1. Name sector module **Sector_1** (or whatever) ->  *Variable name*
2. Name trigger **Sector_1_Trigger** (or whatever) ->  *Variable name*
3. In module expression field

```
{
    if((side _x) isEqualTo (_this select 1)) then 
    {
        [500,0] remoteExecCall ["HG_fnc_addOrSubCash",_x,false];
    };
} forEach (list Sector_1_Trigger);
```

Breakdown:

We do that with a forEach loop by iterating through the units in the trigger area:

**(list Sector_1_Trigger)** -> List of units (array) that would activate given trigger, in this case Sector_1_Trigger

**_x** -> Represents the iterating index in the units array

But we only want the units that belong to the team that captured the sector so we check if the unit side is equal to the side that captured it:

**(side _x) isEqualTo (_this select 1)**

_this select 1 is a passed param in module expression

```
_this select 0 = module
_this select 1 = ownerSide
_this select 2 = previousOwnerSide
```

Then we reward those guys using remote execution:

**[500,0] remoteExecCall ["HG_fnc_addOrSubCash",_x,false]**

Hope it helps.

**Comment by Asmodeuz** [comment]
> if((_this select 1) != sideUnknown) then
{
    {
        if((side _x) isEqualTo (_this select 1)) then 
        {
            [500,0] remoteExecCall ["HG_fnc_addOrSubCash",_x,false];
        };
    } forEach (list Sector_1_Trigger);
};

Thank you for offering a helping hand there, this one worked flawlessly!
Nothing more to add or ask about this one.

Cheers!
