### ISSUE TITLE
HUD disappears on single player save/reload

### ISSUE THREAD

**Issue by jpakkanen** [Ppgtjmad/SimpleShops#64]
After saving and reloading (in a single player scenario) the HUD is not rendered back on screen after the game has loaded. 

I'm able to get it back by binding the HG_fnc_HUD function call into an action

[0] remoteExecCall ["HG_fnc_HUD",(owner player),false];

I assume this function should be called after reloading the save.

**Comment by Ppgtjmad** [comment]
Hello @jpakkanen 

I did not think about the saving feature in single player when designing SimpleShops.

I am working on it right now, will post back here soon with the update.

Thanks for your report.

**Comment by Ppgtjmad** [comment]
There you go:

8198684b66beb8825aa2df440a782512637a5a25

**Comment by jpakkanen** [comment]
Perfect, works very well! Thank you for the quick fix!
