### ISSUE TITLE
"Hint cash" not available when HUD is enabled

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#7]
I have just today downloaded the latest version of SimpleShops and it seems that it is not possible to use the "hint cash" (piggy bank icon) functionality anymore.

When hovering mouse over the icon it pops out a message saying _Not available when HUD is enabled_.
See: http://s1370.photobucket.com/user/testusah123/media/hintcashnotavailablewhenHUDisenabled_zpsegvm9wqe.jpg.html
And no matter how one keeps pressing the piggy bank icon no hint of the current amount of money gets displayed.

Is this intentional?

**Comment by Asmodeuz** [comment]
Ahh, it seems that one needs to change the line _enableHUD_ to **false** in HG_Config.h for the "hint cash" functionality to work.

Follow up question would be that what is supposed to be displayed when _enableHUD_ is set to **true**?
Currently I am not seeing anything on my screen regarding SimpleShops.

**Comment by Ppgtjmad** [comment]
Hello,

Yeah it's done on purpose, because when the money in HUD is enabled you don't need the hint cash functionality anymore. But now am thinking about it, it makes sense to enable it again because on some aspect ratios + interface size combo it's possible that the HUD is hidden (out of screen space).

So I enabled it again.

**Comment by Asmodeuz** [comment]
I also think it's better that anyone can at least _hint_ the cash amount if they're suffering from unoforeseen consequences such as that stuff with aspect ratio + interface size.

I did test this and now it indeed is possible to hint the cash amount even when the HUD is enabled.
