### ISSUE TITLE
VASS

### ISSUE THREAD

**Issue by rkleczek457** [Ppgtjmad/SimpleShops#71]
I am very confused with how to make this mod/scenario work in the eden editor and so i would like to know.

**Comment by Ppgtjmad** [comment]
Hello @rkleczek457 

You can get the scenario on Steam https://steamcommunity.com/sharedfiles/filedetails/?id=2677587435

Then you just load it like any other scenarios.

**Comment by rkleczek457** [comment]
Yes @Ppgtjmad but how do I put it in my own custom scenarios?

**Comment by Ppgtjmad** [comment]
Hello @rkleczek457,

I am very very late on this one sorry for that. I am pretty sure you got it figured out since then.

I am just leaving this link here for reference : https://github.com/Ppgtjmad/SimpleShops/wiki/implementation

Thank you.
