### ISSUE TITLE
File HG_Tags missing? Kill counter/xp not working

### ISSUE THREAD

**Issue by indica-inhaler** [Ppgtjmad/SimpleShops#75]
Want to start with this mod is a fantastic masterpiece. However, every time I've booted the game, Arma says there is an issue with "HG_Tags" not being available as needed. I've looked through all the files and cannot find one with that name.  I did however find HG>>FUNCTIONS>>CLIENT>>TAGS>>fn_playerTags.sqf. I am not sure if this is the incorrect name, or if I am missing HG_Tags. 

The other issue I have is when I get kills (because it seems to run fine without HG_Tags regardless), the hud interface does not count them, and I am not rewarded XP. I can't help but think this and HG_Tags could be related but I also would understand if it is another issue. I could have even done something incorrectly on install.

Edit: I opened to check the info I gave, Arma says HG_Tags is a resource. I'm not entirely sure if that is just a file or a few lines. Either way, I redownloaded the zip file from here again, reinstalled it the same way and HG_Tags is still "missing" and the kill/xp counter is not counting either.

**Comment by Ppgtjmad** [comment]
Hi @indica-inhaler,

**HG_Tags** is a resource and is defined under the **RscTitles** class in your **description.ext** file.

You can find the file here -> [HG_Tags.h](https://github.com/Ppgtjmad/SimpleShops/blob/master/HG/UI/Dialogs/HG_Tags.h)

Make sure you added the required lines to your [description.ext](https://github.com/Ppgtjmad/SimpleShops/wiki/implementation) to fix this issue.

Next is the XP not being rewarded, I'll need some logs to pinpoint where it fails, can you provide that?

**Comment by indica-inhaler** [comment]
Thank you for the quick response!! Yes, my description.exe was somehow missing the hg_tags line. But that is wonderfully fixed now! 

I think this is the log you are referring to, but I am a total noob to scripting things like in Arma, so bear with me if I've grabbed the wrong thing. This is from the specific mission in question:

16:01:05  Mission file: TPW%20Trial
16:01:05  Mission world: takistan
16:01:05  Mission directory: C:\Users\User\Documents\Arma 3 - Other Profiles\Indica%20Inhaler\missions\TPW%20Trial.takistan\
16:01:05 EPE manager release (0|5|0)
16:01:07 [CBA] (xeh) INFO: [31484,1160.74,0] PreInit started. v3.15.8.220912
16:01:07 [CBA] (xeh) WARNING: One or more children of class CAManBase do not support Extended Event Handlers. Fall back to loop.
16:01:07 [CBA] (settings) INFO: Reading settings from settings file.
16:01:07 [CBA] (settings) INFO: Finished reading settings from settings file.
16:01:07 [ACE] (common) INFO: Parsed Settings Configs [1.0 ms]
16:01:08 [CBA] (xeh) INFO: [31484,1161.42,0] PreInit finished.
16:01:09 [CBA] (xeh) INFO: [31493,1162.59,0] PostInit started. MISSIONINIT: missionName=TPW%20Trial, missionVersion=54, worldName=takistan, isMultiplayer=false, isServer=true, isDedicated=false, CBA_isHeadlessClient=false, hasInterface=true, didJIP=false
16:01:09 [CBA] (versioning) INFO: [31493,1162.65,0] VERSIONING:cba=3.15.8.220912, zen=1.12.2.30, ace=3.15.2.69
16:01:09 [ACE] (common) INFO: ACE is version 3.15.2.69 - CBA is version 3.15.8.220912 (min required 3.15.7)
16:01:09 [ACE] (common) INFO: Extension version: ace_break_line: 3.8.4-ef4d289
16:01:09 [ACE] (common) INFO: Extension version: ace_clipboard: 3.8.4-ef4d289
16:01:09 [ACE] (common) INFO: Extension version: ace_artillerytables: 3.13.0-f5aa320
16:01:09 [ACE] (common) INFO: Extension version: ace_fcs: 3.8.4-ef4d289
16:01:09 [ACE] (common) INFO: Extension version: ace_advanced_ballistics: 3.12.0-8ddde18
16:01:09 [CBA] (xeh) INFO: [31493,1162.97,0] PostInit finished.
16:01:09 [CBA] (optics) INFO: Scripted camera restarted.
16:01:09 [ACE] (common) INFO: Settings initialized.
16:01:09 [ACE] (common) INFO: 13 delayed functions running.
16:01:10  Mission id: c8a56c11e9973443779dc3437a07b30262c7b512
16:01:12 Cannot create non-ai vehicle ebs,
16:01:37 [CBA] (xeh) INFO: missionNamespace processed [false]
16:01:37 [CBA] (xeh) INFO: [33019,1190.61,0] PreInit started. v3.15.8.220912
16:01:37 [CBA] (xeh) WARNING: One or more children of class CAManBase do not support Extended Event Handlers. Fall back to loop.
16:01:37 [CBA] (settings) INFO: Reading settings from settings file.
16:01:37 [CBA] (settings) INFO: Finished reading settings from settings file.
16:01:37 [ACE] (common) INFO: Parsed Settings Configs [1.0 ms]
16:01:38 [CBA] (xeh) INFO: [33019,1191.3,0] PreInit finished.

**Comment by indica-inhaler** [comment]
I did note the warning for "CAManBase", however I cannot locate that in the config viewer in the editor with the rest of the "CA" things, and do not exactly know what it is talking about. If it is unrelated to this, then I don't see how it could be an issue for now.

**Comment by indica-inhaler** [comment]
okay will do, sorry for the late response. Has been a tough week outside of arma.
