### ISSUE TITLE
extdb

### ISSUE THREAD

**Issue by YukikazeMua** [Ppgtjmad/SimpleShops#78]
When I am using extdb, if I restart the server, the "Active" in the database will all be reset to 0

**Comment by Ppgtjmad** [comment]
Hi @YukikazeMua 

That's the way it should be.

When your server restarts there may be some owned vehicles that players forgot to park or didn't have the time to.
So there's a function that resets the "Active" status in the database. Without it, players would not be able to see their vehicles in the garage dialog.

The "Active" status is set to 1 when you retrieve a vehicle from the garage, it is set to 0 when you park it.

**Comment by YukikazeMua** [comment]
However, if the player's vehicle is destroyed, the reset server "Active" will still reset to 0, and the player can regain the destroyed vehicle after restarting the server

**Comment by Ppgtjmad** [comment]
Please try this and report back -> https://github.com/Ppgtjmad/SimpleShops/commit/d49575f7be26eb3e5fa3c5de9605b6855ef2f7b4

**Comment by YukikazeMua** [comment]
try

**Comment by YukikazeMua** [comment]
"Alive" does not change to 0 when the vehicle is destroyed

**Comment by Ppgtjmad** [comment]
It does work here, make sure you do all the required modifications according to this commit https://github.com/Ppgtjmad/SimpleShops/commit/d49575f7be26eb3e5fa3c5de9605b6855ef2f7b4

Double and triple check if needed.

**Comment by YukikazeMua** [comment]
"Alive" is 1 , "Active" is 0, but there is no vehicle in the player's garage

**Comment by YukikazeMua** [comment]
Even if the player just saved the vehicle

**Comment by YukikazeMua** [comment]
"Alive" works, and "Active" doesn't work

**Comment by Ppgtjmad** [comment]
My bad -> https://github.com/Ppgtjmad/SimpleShops/commit/ea7b8aa540b0a1fe5c69f49c7f5fc4eab639de14

**Comment by YukikazeMua** [comment]
its working!

**Comment by YukikazeMua** [comment]
thx

**Comment by YukikazeMua** [comment]
Now there is a new issue, I need to refresh the garage many times to display the vehicle

**Comment by Ppgtjmad** [comment]
Share your logs please

**Comment by YukikazeMua** [comment]
[12-43-14.log](https://github.com/Ppgtjmad/SimpleShops/files/11238861/12-43-14.log)

**Comment by Ppgtjmad** [comment]
There's nothing related to your issue in there but one thing that's problematic, change your HG_Vehicles.Classname column length to 255 characters instead of 32.

Also share your RPT logs.

**Comment by YukikazeMua** [comment]
I'm on the server and it takes a few hits to refresh before the garage vehicle appears

**Comment by YukikazeMua** [comment]
[arma3server_x64_2023-04-15_18-34-59.txt](https://github.com/Ppgtjmad/SimpleShops/files/11239854/arma3server_x64_2023-04-15_18-34-59.txt)

**Comment by Ppgtjmad** [comment]
Nothing to see here either and I can't reproduce the issue you're having on my end.

I'd recommend you start fresh and report back.

**Comment by YukikazeMua** [comment]
This problem does not affect for the time being, just shut it down

**Comment by YukikazeMua** [comment]
If the player has used the vehicle, the vehicle's "Alive" will not change to 0
