### ISSUE TITLE
extdb

### ISSUE THREAD

**Issue by YukikazeMua** [Ppgtjmad/SimpleShops#79]
If the player has used a vehicle, "Alive" will not change to 0 when the vehicle is destroyed

**Comment by Ppgtjmad** [comment]
@YukikazeMua

I can't reproduce the issue here, can you provide some logs (DB and RPT) please.

**Comment by YukikazeMua** [comment]
[0-47-10.log](https://github.com/Ppgtjmad/SimpleShops/files/11375821/0-47-10.log)
[arma3server_x64_2023-05-03_00-45-40.txt](https://github.com/Ppgtjmad/SimpleShops/files/11375823/arma3server_x64_2023-05-03_00-45-40.txt)

**Comment by Ppgtjmad** [comment]
Nothing I can see here. 
Does it work when testing locally i.e not on a dedicated server?

**Comment by YukikazeMua** [comment]
i cant use extdb on my locally

**Comment by YukikazeMua** [comment]
That in this way, if I set up (storeVehiclesOnDisconnect = false), so when I restart don't make an Active to "0"

**Comment by YukikazeMua** [comment]
That in this way, if I set up (storeVehiclesOnDisconnect = false), so when I restart don't make an Active to "0"

**Comment by YukikazeMua** [comment]
@Ppgtjmad That in this way, if I set up (storeVehiclesOnDisconnect = false), so when I restart don't make an Active to "0"
