### ISSUE TITLE
Cash display is gone from the bottom right corner

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#8]
As the topic states, with the latest SimpleShops version I downloaded just today, the amount of cash is not displayed anymore on the bottom right corner of the screen.

Does this have something to do with the line _enableHUD_ in HG_Config.h?

**Comment by Ppgtjmad** [comment]
Hello,

Works fine here as long as the **enableHUD** token is set to true.

**Comment by Asmodeuz** [comment]
Downloaded new version with the latest changes and now the cash display is there like it used to be!
