### ISSUE TITLE
Potential issue with Gear Shop "Remove Gear" button 

### ISSUE THREAD

**Issue by BrianV1981** [Ppgtjmad/SimpleShops#82]
I think I found an issue with the gear shop deleting "removed" items.

Load into the example mission, select gear shop, and remove all gear utilizing the "remove gear" button.

Purchase one single item, and all gear will be missing that was removed except the item slot that you purchased. i.e. if you use the remove gear button on a vest, and buy a vest, your original vest will transfer to the crate. however, all other items removed with the remove gear function will be lost.

**Comment by Ppgtjmad** [comment]
Hello @BrianV1981,

Thanks for reporting this unintended behaviour. I'm on it 👍

**Comment by Ppgtjmad** [comment]
A fix is on its way, either tonight or tomorrow.

**Comment by Ppgtjmad** [comment]
@BrianV1981,

Can you try and report back?

THank you.

**Comment by BrianV1981** [comment]
Initial testing shows that the new button is working as expected. If I am viewing a potential item to buy, I can then hit the "current equipment" button to revert back to my personal gear.

However, something happened with the prices, everything in the gear shop is free. I checked, and the config file for the shop does have prices.

Here is the error that pops when I open the gear shop:

```
11:55:16 Error in expression <splay 	          7000 displayCtrl 7003) lbSetValue[_ind,_itemPrice];
		      (	 >
11:55:16   Error position: <lbSetValue[_ind,_itemPrice];
		      (	 >
11:55:16   Error Type Number,Not a Number, expected Number
11:55:16 File C:\Users\kingb\Documents\Arma 3 - Other Profiles\Vasquez\mpmissions\HG's%20Simple%20Shops_v2.VR\HG\Functions\Client\GearShop\fn_xGearSelectionChanged.sqf..., line 32
```

Also, another interesting bug happens when buying the ghillie suit. It will remove your current suit and place all of the items in the container as expected, but after the purchase, a magazine appears in the inventory of the newly purchased ghillie suit. That magazine is a dupe from the current magazine in the gun you are currently equipped with/holding. I can tell it is duped because I tried a few different times with a different amount of bullet counts in the magazine of the gun that I was holding and the bullet count followed the duped magazine after the ghillie suit purchase.

**Comment by Ppgtjmad** [comment]
@BrianV1981 Thanks for reporting.

I don't get that error here using the default mission. I'd double check your implementation to make sure everything is 1:1.

Regarding the duped magazine, I tried and you're right it does get duped. I'm working on a fix right now.

Stay tuned.
