### ISSUE TITLE
The card map cannot be accessed

### ISSUE THREAD

**Issue by catyou123** [Ppgtjmad/SimpleShops#84]
When I connected with extDB3, the entry stuck and I couldn't get into the game and I couldn't edit extDB3's unusable state using 8.0< SQL
[3-7-26.log](https://github.com/user-attachments/files/16788018/3-7-26.log)
This is the server log：
InitSound ...
 3:07:19 InitSound - complete
 3:07:19 PhysX3 SDK Init started ...
 3:07:19 PhysX3 SDK Init ended.
 3:07:21 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.\na3_characters_f
 3:07:21 Loading movesType CfgGesturesMale
 3:07:21 MovesType CfgGesturesMale load time 54.0 ms
 3:07:21 Loading movesType CfgMovesMaleSdr
 3:07:23 Warning: looped for animation: a3\anims_f_epa\data\anim\sdr\cts\hubcleaned\briefing\hubbriefing_loop.rtm differs (looped now 1)! MoveName: hubbriefing_loop
 3:07:23 Warning: looped for animation: a3\anims_f_epa\data\anim\sdr\cts\hubcleaned\briefing\hubbriefing_loop.rtm differs (looped now 0)! MoveName: hubbriefing_ext
 3:07:23 Warning: looped for animation: a3\anims_f_epa\data\anim\sdr\cts\hubcleaned\spectator\hubspectator_stand.rtm differs (looped now 1)! MoveName: hubspectator_stand_contact
 3:07:24 MovesType CfgMovesMaleSdr load time 3001.0 ms
 3:07:24 VoteThreshold must be in 0..1 range. Defaulting to 0.5
 3:07:24 VoteThresholdSameSide must be in 0..1 range. Defaulting to 0.5
Initializing Steam server failed
Unsupported language English in stringtable
Unsupported language English in stringtable
 鉃?Context: mpmissions\__cur_mp.VR\stringtable.xml
Mission 4.VR: Missing 'description.ext::Header'
Starting mission:
 Mission file: 4 (__cur_mp)
 Mission world: VR
 Mission directory: mpmissions\__cur_mp.VR\
"---------------------------------------------------------------------"
"---------------------------------------------------------------------"
CallExtension loaded: extDB3 (F:\SteamLibrary\steamapps\common\Arma 3 Server\@extDB3\extDB3.dll) [x乛]

"extDB3 Loaded"
"---------------------------------------------------------------------"
"---------------------------------------------------------------------"
Error in expression <id"];
Leave Discord or other contact information if you can

**Comment by Ppgtjmad** [comment]
Hello @catyou123,

Can you share the entirety of your Arma 3 log file?

**Comment by catyou123** [comment]
[arma3server_2024-08-29_03-07-13.TXT](https://github.com/user-attachments/files/16798415/arma3server_2024-08-29_03-07-13.TXT)

**Comment by catyou123** [comment]
I found that when I used extdb3 for multiple people, I would not be able to load the map, and if I was able to do so, extdb3 was not connected and I was still using the extdb3 database in 2021

**Comment by Ppgtjmad** [comment]
I can't find anything related to SimpleShops. 

As you may or may not know I'm not the maintainer of the database extension extDB, the author (Torndeco) abandoned its development years ago around 2015.

Although, I'm actually working on an updated version which will include the new MySQL 8.0 authentication protocol.

For now I'd recommend using MySQL < 8.0 and the x64 version of extDB (included with SimpleShops).

**Comment by catyou123** [comment]
Oh, I'm using MySQL<8.0 and I find that when I'm playing multiplayer without extDB, I can't load maps. Like what's keeping me connected to steam

**Comment by catyou123** [comment]
It seems that he can only access the map through the LAN. I tried to change the device, but this also happened

**Comment by catyou123** [comment]
![2ced007dc914ef7eb33738f0d3f704ba](https://github.com/user-attachments/assets/9bc4c10d-0016-45d8-8d98-983bd45ce132)
![929e5bfb4dec6eb4c355957f89510710](https://github.com/user-attachments/assets/10ca4f3c-acb7-4388-b628-b65da360d168)
This is the local test picture
