### ISSUE TITLE
extDB3 link to MariaDB

### ISSUE THREAD

**Issue by HomelessMage** [Ppgtjmad/SimpleShops#86]
I'm running SimpleShops on Ubuntu 22.04 LTS, stable Arma 3, but facing an issue with linking extDB3 with MariaDB;
Arma RPT:
```
"extDB3 Loaded"
"extDB3: Version: 1.032"
"extDB3: Error Failed to Connect to Database: [0,""Database Connection Error""]"
```
Checking extDB3 logs:
```
extDB3: Found extdb3-conf.ini
extDB3: Detected 16 Cores, Setting up 6 Worker Threads
[18:42:56 +03:00] [Thread 132371] extDB3: MariaDBConnectorException: HG: Can't initialize character set utf8 (path: /usr/share/mysql/charsets/)
```
Action done:
- purged and reinstalled MariaDB and extDB3
 
I'm not sure whether this is related to MariaDB, extDB3 or SimpleShops, as I can connect to a database using an SQL client. Maybe you could provide any suggestions?

Further troubleshooting done:
Ran a query in MariaDB to show the active charset:
```
MariaDB [(none)]> SHOW VARIABLES LIKE 'character_set_server';
+----------------------+---------+
| Variable_name        | Value   |
+----------------------+---------+
| character_set_server | utf8mb4 |
+----------------------+---------+
```
`$ ls /usr/share/mysql/charsets`
```
armscii8.xml
ascii.xml
cp1250.xml
cp1251.xml
cp1256.xml
cp1257.xml
cp850.xml
cp852.xml
cp866.xml
dec8.xml
geostd8.xml
greek.xml
hebrew.xml
hp8.xml
Index.xml
keybcs2.xml
koi8r.xml
koi8u.xml
latin1.xml
latin2.xml
latin5.xml
latin7.xml
macce.xml
macroman.xml
swe7.xml
```

**Comment by HomelessMage** [comment]
Further troubleshooting done:
Ran a query in MariaDB to show the active charset:
```
MariaDB [(none)]> SHOW VARIABLES LIKE 'character_set_server';
+----------------------+---------+
| Variable_name        | Value   |
+----------------------+---------+
| character_set_server | utf8mb4 |
+----------------------+---------+
```
`$ ls /usr/share/mysql/charsets`
```
armscii8.xml
ascii.xml
cp1250.xml
cp1251.xml
cp1256.xml
cp1257.xml
cp850.xml
cp852.xml
cp866.xml
dec8.xml
geostd8.xml
greek.xml
hebrew.xml
hp8.xml
Index.xml
keybcs2.xml
koi8r.xml
koi8u.xml
latin1.xml
latin2.xml
latin5.xml
latin7.xml
macce.xml
macroman.xml
swe7.xml
```

**Comment by HomelessMage** [comment]
Further troubleshooting:
- uninstalled MariaDB
- installed MySQL
This seemed to fix the issue. Not sure what had happened with MariaDB connector.

**Comment by Ppgtjmad** [comment]
> Further troubleshooting:
> 
> * uninstalled MariaDB
> * installed MySQL
> 
> This seemed to fix the issue. Not sure what had happened with MariaDB connector.

Hello @HomelessMage 

You're absolutely right, extDB shouldn't be used with MariaDB connector despite what is said in the readme file and that's because the extension hasn't been updated in ages.

I do not have/own the source files and the original author is nowhere to be found therefor I can't do anything about it. Maybe it's time to find another DB extension that works no matter what connector is being used.
