### ISSUE TITLE
Error Missing ; in fn_clientInitialization.sqf

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#9]
Having downloaded the latest version of SimpleShops just today it seems that something was introduced with it.

When launching the SimpleShops test mission (as Multiplayer) from Arma 3 editor an error gets displayed. 
See: http://s1370.photobucket.com/user/testusah123/media/Error_missing_semicolon_zpslymhygoa.jpg.html
The error seems to be pointing to _fn_clientInitialization.sqf_ file where apparently a semicolon is missing thus displaying the error message

**Comment by Ppgtjmad** [comment]
Hello,

Just fixed it, thanks for the report as always :+1:

**Comment by Asmodeuz** [comment]
Latest available version got this one fixed also, so no more error messages about this one! 👍
